import { StyleSheet } from "react-native";
import { SPACING } from "../../constants/Colors";

export const styles = StyleSheet.create({
  professionalBalanceWrapper: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
  },
  professionalBalanceCard: {
    borderRadius: 20,
    padding: SPACING.xl,
    position: "relative",
    overflow: "hidden",
  },
  professionalBalanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: SPACING.lg,
  },
  professionalGreeting: {
    fontSize: 16,
    fontWeight: "600",
    color: "rgba(255,255,255,0.8)",
    marginBottom: 4,
  },
  professionalBalanceLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "rgba(255,255,255,0.6)",
  },
  professionalBalanceIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  professionalBalanceMain: {
    marginBottom: SPACING.lg,
  },
  professionalBalanceAmount: {
    fontSize: 36,
    fontWeight: "900",
    color: "white",
    letterSpacing: -1,
    marginBottom: SPACING.sm,
  },
  professionalBalanceBreakdown: {
    marginBottom: SPACING.md,
  },
  professionalBalanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
  },
  professionalBalanceItem: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  professionalBalanceItemLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "rgba(255,255,255,0.7)",
    marginLeft: 6,
    marginRight: 8,
  },
  professionalBalanceItemValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "white",
  },
  professionalManualBalanceIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: SPACING.sm,
  },
  professionalManualBalanceText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#F59E0B",
    marginLeft: 4,
  },
  professionalBalanceMetrics: {
    flexDirection: "row",
    alignItems: "center",
  },
  professionalBalanceChange: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  professionalChangeIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(16,185,129,0.2)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  professionalChangeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#10B981",
  },
  professionalChangeLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "rgba(255,255,255,0.6)",
  },
  professionalCachedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: "flex-start",
    gap: 6,
  },
  professionalCachedText: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.8)",
  },
  professionalDecoration1: {
    position: "absolute",
    top: -20,
    right: -20,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  professionalDecoration2: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  professionalDecoration3: {
    position: "absolute",
    top: 60,
    right: -15,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 16,
    width: "100%",
    maxWidth: 400,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1F2937",
  },
  modalCloseButton: {
    padding: 4,
  },
  modalBody: {
    padding: 20,
  },
  modalLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#374151",
    marginBottom: 12,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: "#F9FAFB",
    marginBottom: 12,
  },
  modalHint: {
    fontSize: 14,
    color: "#6B7280",
    lineHeight: 20,
  },
  modalFooter: {
    flexDirection: "row",
    padding: 20,
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  modalCancelButton: {
    backgroundColor: "#F3F4F6",
  },
  modalCancelButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#374151",
  },
  modalSaveButton: {
    backgroundColor: "#6366F1",
  },
  modalSaveButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: "white",
  },
  modalClearButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    gap: 8,
  },
  modalClearButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#EF4444",
  },
  // Inline editing styles
  balanceTouchable: {
    // Make the balance touchable for inline editing
  },
  inlineEditContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  inlineEditInput: {
    flex: 1,
    fontSize: 32,
    fontWeight: "700",
    color: "white",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  inlineEditButtons: {
    flexDirection: "row",
    gap: 8,
  },
  inlineEditButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  inlineEditSaveButton: {
    backgroundColor: "rgba(16, 185, 129, 0.3)",
  },
});
