// Auto-detection keywords for transaction categorization
// This file contains keyword mappings for automatic category detection

export const expenseKeywords = {
  food: [
    "restaurant",
    "cafe",
    "coffee",
    "lunch",
    "dinner",
    "breakfast",
    "food",
    "pizza",
    "burger",
    "mcdonalds",
    "kfc",
    "subway",
    "starbucks",
    "costa",
    "pret",
    "nandos",
    "wagamama",
    "dominos",
    "just eat",
    "deliveroo",
    "ubereats",
    "pizza hut",
    "burger king",
    "five guys",
    "byron",
    "honest burger",
    "gourmet burger",
    "frankie & bennys",
    "toby carvery",
    "harvester",
    "weatherspoons",
    "wetherspoons",
    "spoons",
    "greene king",
    "fullers",
    "youngs",
    "pizza express",
    "zizzi",
    "ask italian",
    "bella italia",
    "prezzo",
    "carluccios",
    "cote",
    "bill's",
    "cafe rouge",
    "cafe nero",
    "nero",
    "tim hortons",
    "dunkin",
    "krispy kreme",
    "greggs",
    "pret a manger",
    "leon",
    "wasabi",
    "itsu",
    "yo sushi",
    "sushi",
    "chinese",
    "indian",
    "curry",
    "thai",
    "japanese",
    "korean",
    "mexican",
    "italian",
    "french",
    "spanish",
    "greek",
    "turkish",
    "lebanese",
    "fish and chips",
    "chippy",
    "kebab",
    "doner",
    "chicken shop",
    "nando's",
    "peri peri",
    "chicken cottage",
    "morley's",
    "dixy chicken",
    "popeyes",
    "wingstop",
    "taco bell",
    "chipotle",
    "shake shack",
    "wendy's",
    "arby's",
    "white castle",
    "culver's",
    "sonic",
    "jack in the box",
    "whataburger",
    "fatburger",
    "johnny rockets",
    "red robin",
    "applebee's",
    "chili's",
    "olive garden",
    "outback steakhouse",
    "texas roadhouse",
    "longhorn steakhouse",
    "ruth's chris",
    "morton's",
    "capital grille",
    "flemings",
    "smith & wollensky",
    "peter luger",
    "keens",
    "gallagher's",
    "wolfgang puck",
    "bobby flay",
    "gordon ramsay",
    "jamie oliver",
    "hugh fearnley-whittingstall",
    "nigella lawson",
    "delia smith",
    "mary berry",
    "paul hollywood",
    "prue leith",
    "monica galetti",
    "marco pierre white",
    "heston blumenthal",
    "ferran adria",
    "rene redzepi",
    "massimo bottura",
    "alain ducasse",
    "joel robuchon",
    "thomas keller",
    "daniel boulud",
    "jean-georges",
    "eric ripert",
    "david chang",
    "anthony bourdain",
    "julia child",
    "james beard",
    "jacques pepin",
    "marcus samuelsson",
    "jose andres",
  ],
  transport: [
    "uber",
    "lyft",
    "taxi",
    "bus",
    "train",
    "tube",
    "metro",
    "transport for london",
    "london underground",
    "transport",
    "travel",
    "petrol",
    "fuel",
    "parking",
    "toll",
    "national rail",
    "trainline",
    "avanti",
    "gwr",
    "lner",
    "southern rail",
    "thameslink",
    "southeastern",
    "greater anglia",
    "scotrail",
    "transpennine",
    "crosscountry",
    "chiltern",
    "c2c",
    "merseyrail",
    "tram",
    "oyster",
    "contactless",
    "national express",
    "megabus",
    "stagecoach",
    "first bus",
    "arriva",
    "citymapper",
    "bolt",
    "freenow",
    "addison lee",
    "blacklane",
    "gett",
    "zip car",
    "enterprise",
    "hertz",
    "europcar",
    "avis",
    "sixt",
  ],
  shopping: [
    "shop",
    "store",
    "amazon",
    "ebay",
    "asos",
    "h&m",
    "zara",
    "primark",
    "next",
    "m&s",
    "marks & spencer",
    "boots",
    "superdrug",
    "argos",
    "currys",
    "john lewis",
    "debenhams",
    "house of fraser",
    "selfridges",
    "harrods",
    "fortnum & mason",
    "liberty",
    "tk maxx",
    "tkmaxx",
    "sports direct",
    "jd sports",
    "foot locker",
    "decathlon",
    "topshop",
    "topman",
    "river island",
    "new look",
    "h&m",
    "uniqlo",
    "cos",
    "& other stories",
    "monki",
    "weekday",
    "mango",
    "massimo dutti",
    "bershka",
    "pull & bear",
    "stradivarius",
    "gap",
    "banana republic",
    "matalan",
    "the range",
    "b&m",
    "b&m bargains",
    "home bargains",
    "poundland",
    "poundworld",
    "wilko",
    "ryman",
    "whsmith",
    "waterstones",
    "hmv",
    "cex",
    "carphone warehouse",
    "ee",
    "o2",
    "vodafone",
    "three",
    "apple store",
    "samsung",
    "dixons",
    "pc world",
    "comet",
    "ao.com",
  ],
  entertainment: [
    "cinema",
    "movie",
    "youtube",
    "gaming",
    "game",
    "entertainment",
    "fun",
    "leisure",
    "pub",
    "bar",
    "club",
    "theatre",
    "concert",
    "gig",
    "show",
  ],
  bills: [
    "bill",
    "electricity",
    "gas",
    "water",
    "council",
    "rent",
    "mortgage",
    "insurance",
    "phone",
    "internet",
    "broadband",
    "sky",
    "virgin",
    "virgin media",
    "british telecom",
    "utility",
    "utilities",
    "british gas",
    "edf",
    "eon",
    "e.on",
    "sse",
    "scottish power",
    "npower",
    "bulb",
    "octopus",
    "octopus energy",
    "ovo",
    "ovo energy",
    "shell energy",
    "utilita",
    "so energy",
    "green energy",
    "thames water",
    "severn trent",
    "anglian water",
    "yorkshire water",
    "united utilities",
    "welsh water",
    "south west water",
    "wessex water",
    "southern water",
    "northumbrian water",
    "council tax",
    "halifax",
    "nationwide",
    "barclays",
    "lloyds",
    "hsbc",
    "santander",
    "natwest",
    "rbs",
    "tsb",
    "metro bank",
    "monzo",
    "starling",
    "revolut",
    "wise",
    "transferwise",
    "direct debit",
    "standing order",
    "aviva",
    "axa",
    "admiral",
    "confused",
    "comparethemarket",
    "gocompare",
    "moneysupermarket",
    "direct line",
    "churchill",
    "aa",
    "rac",
    "green flag",
    "esure",
    "hastings direct",
    "lv",
    "more than",
    "tesco insurance",
    "sainsburys insurance",
    "post office insurance",
    "bupa",
    "axa ppp",
    "vitality",
    "benenden",
    "simply health",
    "denplan",
  ],
  healthcare: [
    "doctor",
    "dentist",
    "pharmacy",
    "medicine",
    "health",
    "medical",
    "hospital",
    "clinic",
    "gp",
    "prescription",
    "chemist",
  ],
  education: [
    "school",
    "university",
    "college",
    "course",
    "book",
    "education",
    "learning",
    "tuition",
    "student",
  ],
  travel: [
    "hotel",
    "flight",
    "airline",
    "booking",
    "airbnb",
    "holiday",
    "vacation",
    "trip",
    "travel",
    "abroad",
  ],
  groceries: [
    "grocery",
    "supermarket",
    "food shop",
    "weekly shop",
    "shopping",
    "fresh",
    "organic",
    "tesco",
    "sainsbury's",
    "sainsburys",
    "asda",
    "morrisons",
    "aldi",
    "lidl",
    "waitrose",
    "co-op",
    "coop",
    "iceland",
    "farmfoods",
    "marks & spencer",
    "m&s",
    "marks and spencer",
    "ocado",
    "booths",
    "budgens",
    "nisa",
    "spar",
    "londis",
    "premier",
    "costco",
    "makro",
  ],
  fuel: [
    "petrol",
    "diesel",
    "fuel",
    "gas station",
    "shell",
    "bp",
    "esso",
    "texaco",
  ],
  subscriptions: [
    "subscription",
    "monthly",
    "annual",
    "premium",
    "pro",
    "netflix",
    "spotify",
    "amazon prime",
    "disney",
    "apple music",
    "youtube premium",
  ],
};

export const incomeKeywords = {
  salary: [
    "salary",
    "wage",
    "pay",
    "income",
    "work",
    "job",
    "employment",
    "payroll",
  ],
  freelance: [
    "freelance",
    "contract",
    "consulting",
    "gig",
    "project",
    "client",
  ],
  business: ["business", "company", "revenue", "sales", "profit", "income"],
  investment: [
    "investment",
    "dividend",
    "interest",
    "return",
    "profit",
    "stocks",
    "shares",
  ],
  rental: ["rental", "rent", "property", "tenant", "lease"],
  gift: ["gift", "present", "donation", "charity", "birthday", "christmas"],
};
